### PR TITLE
Sending Invite Admin Email

### PR DESCRIPTION
**Pull request by mmonday0**

### CODE REVIEW

**Comment by LikhitaPulijala** [comment]
This issue is still going on(as on 5th Feb, 2024). There is progress on invite mail and password setup.

**Comment by LikhitaPulijala** [comment]
Could you provide additional details/description regarding the progress made on the task?

**Comment by LikhitaPulijala** [comment]
Checks are failing, please look into them.

**Comment by mmonday0** [comment]
In this most recent commit, several changes were made. Instead of trying to write the user to the database in the account-popover.js file, now the user will be sent an email with the link to the firebase-register page. When the user clicks the link, the register page will not show the "Status" field. This is because the user will automatically be given "Admin" status upon Submitting. 
Progress to be made:
- send email with custom register page link to the new admin with the query parameter containing the new admin email address
- write "Admin" status to firebase on firebase-register page when new admins register

**Pull request closed without merging**
